import type { Metadata } from "next";
import { Trade_Winds } from "next/font/google";
import "./globals.css";

const tradeWinds = Trade_Winds({ weight: "400", style: "normal", subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Choose Your Own Prompt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tradeWinds.className}>{children}</body>
    </html>
  );
}
